version: '3.8'

services:
  backend:
    image: kevlargroup/psn-rwanda-backend:latest
    container_name: psn-rwanda-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Database configuration
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/psn_rwanda
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      # Email configuration
      - SPRING_MAIL_HOST=mail.infomaniak.com
      - SPRING_MAIL_PORT=465
      - SPRING_MAIL_USERNAME=info@oneclic.vet
      - SPRING_MAIL_PASSWORD=Infooneclic123!!
      - APP_NOTIFICATION_PROVIDER_EMAIL=daveleo250@gmail.com
      # File storage
      - APP_FILE_UPLOAD_DIR=/app/uploads
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    networks:
      - psn-network

  db:
    image: postgres:15-alpine
    container_name: psn-rwanda-postgres
    restart: always
    environment:
      - POSTGRES_DB=psn_rwanda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psn-db-data:/var/lib/postgresql/data
    networks:
      - psn-network

networks:
  psn-network:
    driver: bridge

volumes:
  psn-db-data: 